name: csgm
channels:
  - pytorch
  - nvidia
dependencies:
  - pytorch
  - pytorch-cuda=11.8
  - pip
  - pip:
    - matplotlib
    - pandas
    - numpy
    - scikit-learn
    - tqdm
    - gitpython
    - h5py
    - seaborn
