name: csgm
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python==3.9
  - pytorch::pytorch
  - pytorch::pytorch-cuda==11.8
  - pip
  - pip:
    - matplotlib
    - pandas
    - numpy
    - scikit-learn
    - tqdm
    - gitpython
    - h5py
    - seaborn
