name: csgm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pytorch
  - pip
  - cpuonly
  - pip:
    - matplotlib
    - pandas
    - numpy
    - scikit-learn
    - tqdm
    - gitpython
    - h5py
    - seaborn
